#!/usr/bin/env python
#from dbf import VfpTable
import dbf
import sys
import os
import sqlite3
import argparse
import re
import pdb
parser = argparse.ArgumentParser(description="read and convert visual foxpro database files")
group = parser.add_mutually_exclusive_group()
#group.add_argument("-f", "--fields", action="store_true", help="display field names")
group.add_argument("-n", "--info", action="store_true", help="display dbf info")
group.add_argument("-p", "--pretty", action="store_true", help="display pretty-printed table")
group.add_argument("-t", "--table", action="store_true", help="display tab-separated table")
group.add_argument("-d", "--dump", action="store_true", help="dump table")
group.add_argument("-s", "--sqlite", metavar='DB', help="write to sqlite database file DB")
parser.add_argument("-F", "--force", action="store_true", help="overwrites existing table in sqlite database")
parser.add_argument("-v", "--verbose", action="store_true")
parser.add_argument("-i", "--ignore-errors", action="store_true", help="tell DBF library to ignore typecasting errors")
parser.add_argument("-f", "--fields", help="only use field number n")
parser.add_argument('infiles', metavar='DBF', nargs='+', help="input files in visual foxpro format")
args = parser.parse_args()

conn = None

def onIni():
    global conn, fields
    if args.fields: fields = map(int, args.fields.split(","))
#    pdb.set_trace()
    if args.sqlite:
        print "sqlite: Opening db %s ..." % (args.sqlite)
        conn = sqlite3.connect(args.sqlite)
    
    try:
        for dbfName in args.infiles:
            run(dbfName)
    except sqlite3.Error as e:
        print "sqlite: " + e.args[0]
    finally:
        if args.sqlite:
            print "sqlite: Commit and close ..."
            conn.commit()
            conn.close()


def run(dbfName):
    global conn, fields
    table = dbf.VfpTable(dbfName, codepage='utf8')
    table.open()
    
    if not args.fields: fields = range(len(table.field_names))
    if args.verbose: print "--> " + dbfName + " <--"
    if args.table:
        for fld in fields:
            sys.stdout.write('%s\t'%(table.field_names[fld]))
        print "-------------"
        for rec in table[:min(2, len(table))]:
            for fld in fields:
                sys.stdout.write('%s\t'%(rec[fld]))
            print
            
    elif args.pretty:
        out = [ table.field_names ]
        for el in table:
            out.append([ unicode(s).encode('utf-8').strip() for s in el ])
        print_table(out)
        
    elif args.sqlite:
        netto_name = re.sub('[^A-Za-z0-9]', '_', dbfName).strip('_')
        print "Importing %s into table %s ..." % (dbfName, netto_name)
        cr_stat = "CREATE TABLE IF NOT EXISTS `%s` (`%s`)" % (netto_name, '`,`'.join([table.field_names[f] for f in fields]))
        if args.force: conn.execute('DROP TABLE IF EXISTS `%s` ' % (netto_name))
        try:
            conn.execute(cr_stat)
        except Exception, e:
            print "sqlite: Error creating table %s!" % netto_name
            print "You might want to try the --force option."
            raise e
        
        
        for el in table:
            ins_stat = "INSERT INTO `%s` VALUES ('%s')" % (netto_name, "','".join([ unicode(el[f]).encode('utf-8').strip().replace("'","''") for f in fields ]))
            if args.verbose: print "sqlite: executing: %s" % ins_stat
            conn.execute(ins_stat)
        
    elif args.dump:
        print( "\t%s\t%s\t" % (os.path.getsize(dbfName),dbfName))
        for rec in table:
            for fld in fields:
               print('%s: %s'%(table.field_names[fld], rec[fld]))
            print
    else:
        sys.stdout.write( "%s\n"%str(table))
    table.close()


def print_table(rows):
    """print_table(rows)
 
    Prints out a table using the data in `rows`, which is assumed to be a
    sequence of sequences with the 0th element being the header.
    """
 
    # - figure out column widths
    widths = [ len(max(columns, key=len)) for columns in zip(*rows) ]
    
    #widths =  [len(str(max(i, key=lambda x: len(str(x).strip()))).strip()) for i in zip(header, data)]
    #print widths
    
    # - print the separator
    print('+-'+ '-+-'.join( '-' * width for width in widths ) +'-+')
    # - print the header
    header, data = rows[0], rows[1:]
    print('| '+
        ' | '.join( format(title, "%ds" % width) for width, title in zip(widths, header) )
        +' |')
 
    # - print the separator
    print('|-'+ '-+-'.join( '-' * width for width in widths ) +'-|')
 
    # - print the data
    for row in data:
        print('| '+
            " | ".join( format(cdata, "%ds" % width) for width, cdata in zip(widths, row) )
            +' |')

    # - print the separator
    print('+-'+ '-+-'.join( '-' * width for width in widths ) +'-+')

onIni()

